package com.example.genshin_app.ui.theme.color

import androidx.compose.ui.graphics.Color

val DarkAppColors =
    AppColors(
        anchor = Color(0xFF8AB4F8),
        textButton = Color(0xFF8AB4F8),
        primaryBackground = Color(0xFF121212),
        primaryContainer = Color(0xFF1E1E1E),
        searchBar = Color(0xFF1C1C1C),
        mainTitle = Color(0xFF4D8DFF),
        primaryText = Color(0xFFE0E0E0),
        titleContent = Color(0xFFE0E0E0),
        buttonContainerEnable = Color(0xFF4D8DFF),
        buttonContainerDisable = Color(0xFF2A2A2A),
        buttonContainerError = Color(0xFFEF5350),
        buttonContentEnable = Color(0xFFFFFFFF),
        buttonContentDisable = Color(0xFF9E9E9E),
        deleteButton = Color(0xFFEF5350),
        updateButton = Color(0xFF4D8DFF),
        disabledContainer = Color(0xFF2A2A2A),
        disabledBorder = Color(0xFF2A2A2A),
        disabledText = Color(0xFF9E9E9E),
        focusedBorder = Color(0xFF4D8DFF),
        focusedContainer = Color(0xFF1E1E1E),
        focusedText = Color(0xFFE0E0E0),
        focusedLabel = Color(0xFF4D8DFF),
        focusedPlaceholder = Color(0xFF505050),
        focusedTrailingIcon = Color(0xFF4D8DFF),
        primaryCursor = Color(0xFF4D8DFF),
        unfocusedBorder = Color(0xFF3A3A3A),
        unfocusedContainer = Color(0xFF1C1C1C),
        unfocusedText = Color(0xFFE0E0E0),
        unfocusedLabel = Color(0xFFB0B0B0),
        unfocusedPlaceholder = Color(0xFF9E9E9E),
        unfocusedTrailingIcon = Color(0xFFE0E0E0),
        error = Color(0xFFEF5350),
        errorBorder = Color(0xFFEF5350),
        errorText = Color(0xFFEF5350),
        errorLabel = Color(0xFFEF5350),
        errorCursor = Color(0xFFEF5350),
        errorSupportingText = Color(0xFFEF5350),
        errorTrailingIcon = Color(0xFFEF5350),
        snackbarContainer = Color(0xFF2A2A2A),
        snackbarContent = Color(0xFFFFFFFF),
        snackbarDismiss = Color(0xFFFFFFFF),
        navigationIconContent = Color(0xFFE0E0E0),
        warningIcon = Color(0xFFFFD54F),
        warningButton = Color(0xFFEF5350),
        circularProgress = Color(0xFF4D8DFF),
        horizontalDivider = Color(0xFFFFFFFF),
    )