package com.example.genshin_app.ui.theme.color

import androidx.compose.ui.graphics.Color

val LightAppColors =
    AppColors(
        anchor = Color(0xFF385898),
        textButton = Color(0xFF385898),
        primaryBackground = Color(0xFFF2F4F7),
        primaryContainer = Color(0xFFFFFFFF),
        searchBar = Color(0xFFF0F2F5),
        mainTitle = Color(0xFF0866FF),
        primaryText = Color(0xFF212121),
        titleContent = Color(0xFF212121),
        buttonContainerEnable = Color(0xFF0866FF),
        buttonContainerDisable = Color(0xFFD0D0D0),
        buttonContainerError = Color(0xFFDD3C10),
        buttonContentEnable = Color(0xFFFAFAFA),
        buttonContentDisable = Color(0x80FAFAFA),
        deleteButton = Color(0xFFDD3C10),
        updateButton = Color(0xFF0866FF),
        disabledContainer = Color(0xFFD0D0D0),
        disabledBorder = Color(0xFFD0D0D0),
        disabledText = Color(0x80FAFAFA),
        focusedBorder = Color(0xFF0866FF),
        focusedContainer = Color(0xFFFFFFFF),
        focusedText = Color(0xFF212121),
        focusedLabel = Color(0xFF0866FF),
        focusedPlaceholder = Color(0xFF9E9E9E),
        focusedTrailingIcon = Color(0xFF0866FF),
        primaryCursor = Color(0xFF0866FF),
        unfocusedBorder = Color(0xFFDDDFE2),
        unfocusedContainer = Color(0xFFFAFAFA),
        unfocusedText = Color(0xFF000000),
        unfocusedLabel = Color(0xFF90949C),
        unfocusedPlaceholder = Color(0xFF505050),
        unfocusedTrailingIcon = Color(0xFF212121),
        error = Color(0xFFDD3C10),
        errorBorder = Color(0xFFDD3C10),
        errorText = Color(0xFFDD3C10),
        errorLabel = Color(0xFFDD3C10),
        errorCursor = Color(0xFFDD3C10),
        errorSupportingText = Color(0xFFDD3C10),
        errorTrailingIcon = Color(0xFFDD3C10),
        snackbarContainer = Color(0xFF212121),
        snackbarContent = Color(0xFFFAFAFA),
        snackbarDismiss = Color(0xFFFAFAFA),
        navigationIconContent = Color(0xFF212121),
        warningIcon = Color(0xFFF9A825),
        warningButton = Color(0xFFDD3C10),
        circularProgress = Color(0xFF0866FF),
        horizontalDivider = Color(0xFF000000),
    )